
export type ChannelType = 'AIRBNB' | 'HOLIDU' | 'BOOKINGCOM';

/**The review returned from the store */
export type ReviewType = {
    /**Id autogenerated in the store */
    id: string,
    /**Review header */
    headline: string,
    /**Review comment */
    comment: string,
    /**Review author */
    author: string,
    /**Review positive feedback */
    positiveFeedback: string | null,
    /**Review negative feedback */
    negativeFeedback: string | null,
    /**Review score */
    score: number,
    /**Review channel in uppercase */
    channel: ChannelType,
    /**Review date - example: 2020-08-11T12:20:02.340Z */
    publishedAt: string
}

export type GetReviewsParamsType = Partial<{
    /**An array of channels in uppercase */
    channel: ChannelType[],
    score: number[],
    _page: number,
    _limit: number
}>

/**The review returned from the back-end */
export type GetReviewsResponseType = Omit<ReviewType, 'id'>

/**Parameters that can be sent to the api */
export type ApiParamsType = Record<string, undefined | number | string | (number | string)[]>